measurements:
  - name: Common::WallTime
  - name: Network::Connections
  - name: Network::IOCounters
    parameters:
      per_interface: false
  - name: Memory::Usage
    parameters:
      include_children: false
  - name: CPU::Usage
    parameters:
      include_children: false