# measurements:
#   - name: Common::WallTime
#   - name: Network::Connections
#   - name: Network::IOCounters
#     parameters:
#       per_interface: false
#   - name: Memory::Usage
#     parameters:
#       include_children: false
#   - name: CPU::Usage
#     parameters:
#       include_children: false
#   - name: Information::Environment
#   - name: Information::OperatingSystem
#   - name: Information::Payload

# captures:
#   - name: AWS::S3Capture
#   - name: AWS::EFSCapture
#     parameters:
#       mount_points: ['/tmp']

tracing:
  enabled: True
  trace_outgoing: "*"


exporters:
  - name: Console
  # - name: DashboardUploader
  #   parameters:
  #     endpoint_url: https://faas-profiler.herokuapp.com/api/new
  # - name: S3Uploader
  #   parameters:
  #     bucket: faas-profiler-results
  #     folder: results