service: faas-profiler
frameworkVersion: '3'
provider:
  name: aws
  architecture: arm64
  ecr:
    images:
      hello_world_image:
        path: functions/hello_world
        file: Dockerfile.aws
        buildArgs:
          BASE_IMAGE: faas_profiler_build_image
          FUNCTION_DIR: /function
  region: eu-central-1
  stage: dev
functions:
  hello_world:
    image:
      command: function.handler
      entryPoint: /entry.sh
      name: hello_world_image
