service: faas-profiler
frameworkVersion: '3'
provider:
  name: aws
  architecture: arm64
  region: eu-central-1
  stage: dev
  ecr:
    images:
      hello_world_py_image:
        path: functions/hello_world_py
        file: Dockerfile.aws
        buildArgs:
          BASE_IMAGE: fp_aws_build_image_python-3.8:latest
          FUNCTION_DIR: /function
      hello_world_js_image:
        path: functions/hello_world_js
        file: Dockerfile.aws
        buildArgs:
          BASE_IMAGE: fp_aws_build_image_node-16.14.2:latest
          FUNCTION_DIR: /function
      s3_upload_image:
        path: functions/s3_upload
        file: Dockerfile.aws
        buildArgs:
          BASE_IMAGE: fp_aws_build_image_python-3.8:latest
          FUNCTION_DIR: /function
      s3_download_image:
        path: functions/s3_download
        file: Dockerfile.aws
        buildArgs:
          BASE_IMAGE: fp_aws_build_image_python-3.8:latest
          FUNCTION_DIR: /function
      http_download_efs_image:
        path: functions/http_download_efs
        file: Dockerfile.aws
        buildArgs:
          BASE_IMAGE: fp_aws_build_image_python-3.8:latest
          FUNCTION_DIR: /function
  iamRoleStatements:
  - Effect: Allow
    Action: s3:PutObject
    Resource: arn:aws:s3:::faas-profiler-results/*
functions:
  hello_world_py:
    iamRoleStatements:
    - Effect: Allow
      Action: s3:GetObject
      Resource: arn:aws:s3:::faas-profiler-resources/*
    image:
      command: function.handler
      entryPoint:
      - /usr/local/bin/python
      - -m
      - awslambdaric
      name: hello_world_py_image
  hello_world_js:
    image:
      command: function.handler
      entryPoint:
      - /usr/local/bin/npx
      - aws-lambda-ric
      name: hello_world_js_image
  s3_upload:
    image:
      command: function.handler
      entryPoint:
      - /usr/local/bin/python
      - -m
      - awslambdaric
      name: s3_upload_image
    iamRoleStatements:
    - Effect: Allow
      Action: s3:PutObject
      Resource: arn:aws:s3:::faas-profiler-resources/*
  s3_download:
    image:
      command: function.handler
      entryPoint:
      - /usr/local/bin/python
      - -m
      - awslambdaric
      name: s3_download_image
    iamRoleStatements:
    - Effect: Allow
      Action: s3:GetObject
      Resource: arn:aws:s3:::faas-profiler-resources/*
  http_download_efs:
    image:
      command: function.handler
      entryPoint:
      - /usr/local/bin/python
      - -m
      - awslambdaric
      name: http_download_efs_image
plugins:
- serverless-iam-roles-per-function
