service: benchmarks-empty-profiler

provider:
  name: google
  stage: dev
  memorySize: 1024
  timeout: 10s
  runtime: python38
  region: europe-west3
  project: faas-355111
  credentials: ~/.gcloud/keyfile.json

frameworkVersion: '3'
plugins:
  - serverless-google-cloudfunctions

package:
  patterns:
  - '!**'
  - '!**/**'
  - main.py
  - requirements.txt

functions:
  empty:
    handler: empty
    events:
      - http: path
  