
measurements:
  - name: network::Connections
  - name: network::IOCounters
  - name: memory::LineUsage
  - name: memory::Usage
  - name: cpu::Usage
  - name: information::Environment
  - name: information::OperatingSystem
  - name: disk::IOCounters

# captures:
#   - name: aws::S3Capture
#   - name: aws::EFSCapture
#     parameters:
#       mount_points:
#         - /tmp

exporters:
  - name: common::Console
  # - name: common::Visualizer
  #   parameters:
  #     function_name: fp-visualizer-functions-dev-process_record
  #     region_name: eu-central-1
  - name: common::GCPVisualizerUploader
    parameters:
      project: faas-355111
      bucket_name: faas-profiler-records
      region_name: europe-west3
