#
# Dockerfile for AWS Lambda Python
#

ARG BASE_IMAGE

FROM ${BASE_IMAGE} as build-image
ARG FUNCTION_DIR

#
# Add function-dependent operations here...
#
ADD function.py ${FUNCTION_DIR}
ADD fp_config.yml ${FUNCTION_DIR}

# Build final runtime
FROM ${BASE_IMAGE}
ARG FUNCTION_DIR

WORKDIR ${FUNCTION_DIR}
COPY --from=build-image ${FUNCTION_DIR} ${FUNCTION_DIR}
